# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/GiaKhiem/python-app/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 780)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 900, 780))
        self.label.setStyleSheet("background-color: #F5F5F5;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/GiaKhiem/python-app/ui/../img/original-41d71b37aff8a5479729279fbc6bd47e.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(190, 30, 481, 111))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(44)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(155, 170, 255)")
        self.label_2.setObjectName("label_2")
        self.Txt_email = QtWidgets.QLabel(parent=Form)
        self.Txt_email.setGeometry(QtCore.QRect(300, 260, 131, 41))
        self.Txt_email.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.Txt_email.setFont(font)
        self.Txt_email.setStyleSheet("color:rgb(255, 255, 255)")
        self.Txt_email.setObjectName("Txt_email")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(220, 280, 49, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(210, 280, 49, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(300, 300, 191, 41))
        self.txt_email.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_email.setObjectName("txt_email")
        self.lb = QtWidgets.QLabel(parent=Form)
        self.lb.setGeometry(QtCore.QRect(310, 350, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.lb.setFont(font)
        self.lb.setStyleSheet("color:rgb(255, 255, 255)")
        self.lb.setObjectName("lb")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(300, 400, 231, 61))
        self.txt_password.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_password.setObjectName("txt_password")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(310, 460, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.txt_confirm_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_confirm_password.setGeometry(QtCore.QRect(310, 510, 221, 41))
        self.txt_confirm_password.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_confirm_password.setObjectName("txt_confirm_password")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(480, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(25)
        font.setItalic(False)
        font.setUnderline(False)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("border-radius:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255))")
        self.btn_login.setObjectName("btn_login")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(650, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 255, 39, 255), stop:0.994475 rgba(0, 70, 255, 255))")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 271, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(25)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(310, 640, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(30)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.165746 rgba(99, 255, 0, 255), stop:0.79558 rgba(0, 144, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 10px")
        self.btn_register.setObjectName("btn_register")
        self.btn_eye_p = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_p.setGeometry(QtCore.QRect(480, 420, 51, 21))
        self.btn_eye_p.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/GiaKhiem/python-app/ui/../../../../../Downloads/eye-slash-solid (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_cp.setGeometry(QtCore.QRect(490, 520, 41, 21))
        self.btn_eye_cp.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_cp.setText("")
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setObjectName("btn_eye_cp")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(320, 580, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        font.setBold(True)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.287293 rgba(0, 255, 207, 255), stop:0.834254 rgba(67, 0, 255, 255))")
        self.checkBox.setObjectName("checkBox")
        self.Txt_email_2 = QtWidgets.QLabel(parent=Form)
        self.Txt_email_2.setGeometry(QtCore.QRect(300, 130, 131, 41))
        self.Txt_email_2.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.Txt_email_2.setFont(font)
        self.Txt_email_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.Txt_email_2.setObjectName("Txt_email_2")
        self.txt_name = QtWidgets.QLineEdit(parent=Form)
        self.txt_name.setGeometry(QtCore.QRect(290, 190, 191, 41))
        self.txt_name.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_name.setObjectName("txt_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Create Account"))
        self.Txt_email.setText(_translate("Form", "Email"))
        self.txt_email.setPlaceholderText(_translate("Form", "Please enter your email"))
        self.lb.setText(_translate("Form", "password"))
        self.txt_password.setPlaceholderText(_translate("Form", "please enter your password"))
        self.label_9.setText(_translate("Form", "confirm password"))
        self.txt_confirm_password.setPlaceholderText(_translate("Form", "please confirm your password"))
        self.btn_login.setText(_translate("Form", "log in"))
        self.label_3.setText(_translate("Form", "sign in"))
        self.label_4.setText(_translate("Form", "Weather forecast"))
        self.btn_register.setText(_translate("Form", "Done"))
        self.checkBox.setText(_translate("Form", "Already have an account?"))
        self.Txt_email_2.setText(_translate("Form", "Name"))
        self.txt_name.setPlaceholderText(_translate("Form", "Please enter your name"))
