# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/GiaKhiem/python-app/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(290, 0, 191, 111))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(44)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.Txt_email = QtWidgets.QLabel(parent=Form)
        self.Txt_email.setGeometry(QtCore.QRect(270, 170, 131, 41))
        self.Txt_email.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.Txt_email.setFont(font)
        self.Txt_email.setStyleSheet("color:rgb(255, 255, 255)")
        self.Txt_email.setObjectName("Txt_email")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(220, 280, 49, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(210, 280, 49, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(270, 210, 231, 41))
        self.txt_email.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_email.setObjectName("txt_email")
        self.lb = QtWidgets.QLabel(parent=Form)
        self.lb.setGeometry(QtCore.QRect(270, 260, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.lb.setFont(font)
        self.lb.setStyleSheet("color:rgb(255, 255, 255)")
        self.lb.setObjectName("lb")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(270, 300, 231, 41))
        self.txt_password.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_password.setObjectName("txt_password")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(270, 350, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.txt_confirm_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_confirm_password.setGeometry(QtCore.QRect(270, 380, 241, 41))
        self.txt_confirm_password.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_confirm_password.setObjectName("txt_confirm_password")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(500, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(25)
        font.setItalic(False)
        font.setUnderline(False)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("border-radius:rgb(0, 0, 0);\n"
"color:rgb(0, 0, 0)")
        self.btn_login.setObjectName("btn_login")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(670, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(280, 490, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(30)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"color: white;")
        self.btn_register.setObjectName("btn_register")
        self.btn_eye_p = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_p.setGeometry(QtCore.QRect(460, 390, 51, 21))
        self.btn_eye_p.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/GiaKhiem/python-app/ui/../../../../../Downloads/eye-slash-solid (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_cp.setGeometry(QtCore.QRect(460, 310, 41, 21))
        self.btn_eye_cp.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_cp.setText("")
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setObjectName("btn_eye_cp")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(270, 440, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT")
        font.setPointSize(10)
        font.setBold(True)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color:rgb(0, 0, 0)")
        self.checkBox.setObjectName("checkBox")
        self.Txt_email_2 = QtWidgets.QLabel(parent=Form)
        self.Txt_email_2.setGeometry(QtCore.QRect(280, 80, 131, 41))
        self.Txt_email_2.setMinimumSize(QtCore.QSize(131, 0))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.Txt_email_2.setFont(font)
        self.Txt_email_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.Txt_email_2.setObjectName("Txt_email_2")
        self.txt_name = QtWidgets.QLineEdit(parent=Form)
        self.txt_name.setGeometry(QtCore.QRect(270, 130, 231, 41))
        self.txt_name.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.054, x2:1, y2:0, stop:0 rgba(98, 255, 187, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_name.setObjectName("txt_name")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/GiaKhiem/python-app/ui/../img/photo-1506905925346-21bda4d32df4.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_2.raise_()
        self.Txt_email.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.txt_email.raise_()
        self.lb.raise_()
        self.txt_password.raise_()
        self.label_9.raise_()
        self.txt_confirm_password.raise_()
        self.btn_login.raise_()
        self.label_3.raise_()
        self.btn_register.raise_()
        self.btn_eye_p.raise_()
        self.btn_eye_cp.raise_()
        self.checkBox.raise_()
        self.Txt_email_2.raise_()
        self.txt_name.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Sign up"))
        self.Txt_email.setText(_translate("Form", "Email"))
        self.txt_email.setPlaceholderText(_translate("Form", "Please enter your email"))
        self.lb.setText(_translate("Form", "Password"))
        self.txt_password.setPlaceholderText(_translate("Form", "please enter your password"))
        self.label_9.setText(_translate("Form", "Confirm Password"))
        self.txt_confirm_password.setPlaceholderText(_translate("Form", "please confirm your password"))
        self.btn_login.setText(_translate("Form", "log in"))
        self.label_3.setText(_translate("Form", "sign in"))
        self.btn_register.setText(_translate("Form", "Done"))
        self.checkBox.setText(_translate("Form", "Already have an account?"))
        self.Txt_email_2.setText(_translate("Form", "Name"))
        self.txt_name.setPlaceholderText(_translate("Form", "Please enter your name"))
